apiVersion: v1
kind: Service
metadata:
  name: go-server-service
spec:
  selector:
      app: simple-server-go
  type: NodePort
  ports:
    - port: 6000
      targetPort: 6000
      # pin the nodePort to the one currently allocated in the cluster
      nodePort: 31432

  
